---
- name: file <|> Ensure old netplan configuration is erased
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/netplan/00-installer-config.yaml"
    - "/etc/netplan/50-cloud-init.yaml"
  tags:
    - identify

- name: file <|> Netplan uses NetworkManager
  ansible.builtin.copy:
    src: 01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644
  tags:
    - identify

- name: "service <|> Disable systemd-networkd"
  ansible.builtin.service:
    name: systemd-networkd
    enabled: no
    state: stopped
  notify: reboot <|> Reboot system
