---
- name: managements playbook
  hosts: "fn_management"
  roles:

    # HPC
    - role: bluebanquise.infrastructure.slurm
      tags: slurm_controller
      vars:
        slurm_profile: controller
    - role: bluebanquise.infrastructure.slurm
      tags: slurm_compute
      vars:
        slurm_profile: compute
    - role: bluebanquise.infrastructure.slurm
      tags: slurm_submitter
      vars:
        slurm_profile: submitter
    - role: bluebanquise.infrastructure.flexlm
      tags: flexlm
    - role: bluebanquise.infrastructure.nhc
      tags: nhc
    - role: bluebanquise.infrastructure.lmod
      tags: lmod
