---

- name: mysql_db <|> Create slurm_acct_db database
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: present
    login_host: "{{ slurm_accounting_mysql_login_host | default(omit, true) }}"
    login_port: "{{ slurm_accounting_mysql_login_port | default(omit, true) }}"
    login_user: "{{ slurm_accounting_mysql_login_user | default(omit, true) }}"
    login_password: "{{ slurm_accounting_mysql_login_password | default(omit, true) }}"
  when: slurm_accounting_mysql_create_database

- name: mysql_user <|> Ensure slurm user exists in the database
  community.mysql.mysql_user:
    name: "{{ slurm_accounting_mysql_slurm_user }}"
    password: "{{ slurm_accounting_mysql_slurm_password }}"
    login_host: "{{ slurm_accounting_mysql_login_host | default(omit, true) }}"
    login_port: "{{ slurm_accounting_mysql_login_port | default(omit, true) }}"
    login_user: "{{ slurm_accounting_mysql_login_user | default(omit, true) }}"
    login_password: "{{ slurm_accounting_mysql_login_password | default(omit, true) }}"
    state: present
    priv: 'slurm_acct_db.*:ALL'
    column_case_sensitive: false
  when:
    - slurm_accounting_mysql_create_user
