---
- name: "package <|> Install {{ slurm_packages_to_install['accounting_mysql'] | join(' ') }}"
  ansible.builtin.package:
    name: "{{ slurm_packages_to_install['accounting_mysql'] }}"
    state: present
  tags:
    - package

- name: "template <|> Generate {{ slurm_mysql_cnf_dir }}/slurmdbd.cnf"
  ansible.builtin.template:
    src: slurmdbd.cnf.j2
    dest: "{{ slurm_mysql_cnf_dir }}/slurmdbd.cnf"
    owner: root
    group: root
    mode: 0644
  tags:
    - template
  notify: service <|> restart slurmdbd

- name: file <|> Configure MariaDB to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*=\s*127\.0\.0\.1'
    line: 'bind-address = 0.0.0.0'
    backrefs: yes
  when:
    - ansible_distribution == 'Ubuntu'
  notify: service <|> restart mariadb
  register: mariadb_config

- name: Force handlers
  meta: flush_handlers
  when: mariadb_config.changed
